apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ruby-bot.fullname" . }}-secrets
  labels:
    {{- include "ruby-bot.labels" . | nindent 4 }}
type: Opaque
data:
  bot-token: {{ .Values.secrets.botToken | b64enc | quote }}
  socks-proxy: {{ .Values.secrets.socksProxy | b64enc | quote }} 