name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: romaxa55/ruby_bot/ruby-bot
        tags: latest
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ GITHUB_TOKEN }}
